apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: downloader
  namespace: argo-cd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/tombulled/argo-charts
    path: downloader
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
