apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argo-cd
spec:
  destination:
    namespace: common
    server: https://kubernetes.default.svc
  project: default 
  source: 
    repoURL: https://github.com/tombulled/argo-charts
    path: grafana
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false