apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homer
  namespace: argo-cd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default 
  source: 
    repoURL: https://github.com/tombulled/argo-charts
    path: homer
    targetRevision: feature/uptime-kuma
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false