apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: music-ui
  namespace: argo-cd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default 
  source: 
    repoURL: https://github.com/tombulled/argo-charts
    path: music-ui
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true