apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skyrouter-exporter
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default 
  source: 
    repoURL: https://github.com/tombulled/argo-charts
    path: skyrouter-exporter
    targetRevision: feature/cert-manager
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false